import type { Metadata } from "next";

import { NotificationProvider } from '../app/ui/context/NotificationContext';

import "./globals.scss";
import Notifications from "./ui/components/notifications";

export const metadata: Metadata = {
  title: "ImgEnhancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <NotificationProvider>
      <html lang="en">
        <body
        >
          <main className="main-container">

            {children}

          <Notifications />
          </main>


        </body>
      </html >
    </NotificationProvider>
  );
}
