import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "./ui/components/header";
import Footer from "./ui/components/footer";

import "./globals.scss";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "ImgEnhancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <main className="main-container">

          <Header />

          {children}

          <Footer />
        </main>
        
      </body>
    </html>
  );
}
